graphql:
  spqr:
    gui:
      enabled: false

server:
  port: 7777

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuerUri}
      client:
        registration:
          keycloak:
            client-id: 'app-spring-boot-keycloak-graphql-demo'
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            clientAuthenticationMethod: post
            clientSecret: ea6d508b-77f5-42e3-ab0d-93b7efe9e3ca
            scope: [ 'openid', 'microprofile-jwt' ]
        provider:
          keycloak:
            issuerUri: http://localhost:8080/auth/realms/graphql-demo
            user-name-attribute: preferred_username
  main:
    allow-bean-definition-overriding: true
